-- Run this in Supabase SQL editor

create table if not exists public.saved_chats (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  name text not null,
  messages jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists saved_chats_user_id_created_at_idx
  on public.saved_chats (user_id, created_at desc);

create table if not exists public.shared_answers (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now()
);

create index if not exists shared_answers_slug_idx
  on public.shared_answers (slug);
